name: Docker Build & Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        
      - name: Login DocekrHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build & Push to DocekrHub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
              ${{ secrets.DOCKER_USER }}/github-actions-app:${{ github.ref_name }}
              ${{ secrets.DOCKER_USER }}/github-actions-app:latest