name: Hello

on:
  workflow_dispatch: 
  #push:
  #  branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi to user
        run: echo "hello"
      - name: Say Hi to Username
        run: echo "hello $USER" 
  sysinfo:
    runs-on: ubuntu-slim
    steps:
      - name: Docker & GIT version info
        run: docker --version && git --version
      
