name: Hello

on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi to user
        run: echo "hello"
      - name: Say Hi to Username
        run: 'hello $USER' 
