name: CICD

on:
  workflow_dispatch:

jobs:
  Code:
    runs-on: ubuntu-slim
    steps:
      - name: Building code
        run: echo "Gather code from GH"
  Build:
    needs: Code
    runs-on: ubuntu-slim
    steps:
      - name: Building code from GH
        run: echo "build tool bulding appln"

  Test:
    needs: Build
    runs-on: ubuntu-slim
    steps:
      - name: Testing Application
        run: echo "Testing is in progress..."
             echo "Testing is completed.!"

  Deoloy:
    needs: Test
    runs-on: ubuntu-slim
    steps:
      - name: Deply Application EC2
        run: echo "Deployment is completed"
